name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add these permissions
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install build dependencies
          pip install build pip-tools
          # Install the package with all optional dependencies
          pip install -e ".[dev,test,doc]"
          # Install documentation tools
          pip install pdoc    # Changed from pdoc3 to pdoc

      - name: Generate documentation
        run: |
          # Make sure Python can find the package
          mkdir -p docs
          pdoc -o docs scanpytools || {    # Simplified pdoc command
            echo "Documentation generation failed"
            exit 1
          }
          mkdir -p docs
          PYTHONPATH=$PWD pdoc -o docs scanpytools          # Create .nojekyll file to disable GitHub Pages Jekyll processing
          touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages